services:
  - type: web
    name: file-manager-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT web_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9